/**
 * Credit Card Database
 * Contains detailed information on major US credit cards used for recommendations.
 * Point values used: Chase UR = 1.8¢, Amex MR = 1.8¢, Capital One = 1.5¢, Citi TYP = 1.6¢, Cash = 1¢
 */

const POINT_VALUES = {
  'Chase Ultimate Rewards': 0.018,
  'Amex Membership Rewards': 0.018,
  'Capital One Miles': 0.015,
  'Citi ThankYou Points': 0.016,
  'Cash': 0.01,
  'Discover Cashback': 0.01,
  'United Miles': 0.013,
  'Hilton Points': 0.005,
  'Delta Miles': 0.012,
  'Marriott Points': 0.007,
};

const CARDS = [
  // ── CHASE ──────────────────────────────────────────────────────────────────
  {
    id: 'csr',
    name: 'Chase Sapphire Reserve',
    issuer: 'Chase',
    network: 'Visa',
    annualFee: 550,
    annualCredits: 300, // travel credit
    signupBonus: 60000,
    signupBonusValue: 1080, // 60k × $0.018
    signupBonusSpend: 4000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Chase Ultimate Rewards',
    categories: {
      travel: 3,
      dining: 3,
      chaseTravel: 10,
      everything: 1,
    },
    benefits: [
      '$300 annual travel credit',
      'Priority Pass lounge access (unlimited)',
      'Global Entry / TSA PreCheck credit ($100)',
      'DoorDash DashPass membership',
      'Trip cancellation & interruption insurance',
      'Primary rental car insurance',
      'Hotel collection benefits',
    ],
    applicationRules: {
      rule5_24: true,
      sapphireFamily: true,
      sapphireCooldown: 48,
    },
    type: 'personal',
    creditScore: 'excellent',
    tags: ['travel', 'premium', 'dining', 'chase-ecosystem', 'flagship', 'lounge'],
    ecosystem: 'Chase',
    ecosystemRole: 'hub',
  },
  {
    id: 'csp',
    name: 'Chase Sapphire Preferred',
    issuer: 'Chase',
    network: 'Visa',
    annualFee: 95,
    annualCredits: 50, // $50 hotel credit through Chase Travel
    signupBonus: 60000,
    signupBonusValue: 1080,
    signupBonusSpend: 4000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Chase Ultimate Rewards',
    categories: {
      travel: 2,
      dining: 3,
      chaseTravel: 5,
      onlineShopping: 3,
      streaming: 3,
      everything: 1,
    },
    benefits: [
      '$50 annual hotel credit through Chase Travel',
      'Trip cancellation & interruption insurance',
      'Primary rental car insurance',
      'DoorDash DashPass membership',
      'Lyft Pink membership',
      '10% anniversary points bonus',
    ],
    applicationRules: {
      rule5_24: true,
      sapphireFamily: true,
      sapphireCooldown: 48,
    },
    type: 'personal',
    creditScore: 'good',
    tags: ['travel', 'dining', 'chase-ecosystem', 'mid-tier', 'beginner-friendly'],
    ecosystem: 'Chase',
    ecosystemRole: 'hub',
  },
  {
    id: 'cfu',
    name: 'Chase Freedom Unlimited',
    issuer: 'Chase',
    network: 'Visa',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 200,
    signupBonusValue: 200,
    signupBonusSpend: 500,
    signupBonusMonths: 3,
    rewardsCurrency: 'Chase Ultimate Rewards',
    categories: {
      dining: 3,
      drugstore: 3,
      chaseTravel: 5,
      everything: 1.5,
    },
    benefits: [
      'No annual fee',
      'Points combine with Sapphire for premium transfers',
      'Extended warranty protection',
      'Purchase protection',
    ],
    applicationRules: {
      rule5_24: true,
    },
    type: 'personal',
    creditScore: 'good',
    tags: ['cashback', 'no-fee', 'chase-ecosystem', 'companion'],
    ecosystem: 'Chase',
    ecosystemRole: 'spoke',
  },
  {
    id: 'cff',
    name: 'Chase Freedom Flex',
    issuer: 'Chase',
    network: 'Mastercard',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 200,
    signupBonusValue: 200,
    signupBonusSpend: 500,
    signupBonusMonths: 3,
    rewardsCurrency: 'Chase Ultimate Rewards',
    categories: {
      rotating: 5, // up to $1,500/quarter
      dining: 3,
      drugstore: 3,
      chaseTravel: 5,
      everything: 1,
    },
    benefits: [
      'No annual fee',
      '5% rotating categories (up to $1,500/quarter)',
      'Cell phone protection',
      'Points combine with Sapphire for premium transfers',
    ],
    applicationRules: {
      rule5_24: true,
    },
    type: 'personal',
    creditScore: 'good',
    tags: ['cashback', 'no-fee', 'rotating', 'chase-ecosystem', 'companion'],
    ecosystem: 'Chase',
    ecosystemRole: 'spoke',
  },
  {
    id: 'ink-preferred',
    name: 'Chase Ink Business Preferred',
    issuer: 'Chase',
    network: 'Visa',
    annualFee: 95,
    annualCredits: 0,
    signupBonus: 100000,
    signupBonusValue: 1800,
    signupBonusSpend: 8000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Chase Ultimate Rewards',
    categories: {
      travel: 3,
      shipping: 3,
      advertising: 3,
      telecom: 3,
      everything: 1,
    },
    benefits: [
      '3x on travel, shipping, advertising, telecom (up to $150k/year)',
      'Cell phone protection ($1,000/claim)',
      'Trip cancellation insurance',
      'No foreign transaction fees',
    ],
    applicationRules: {
      rule5_24: true,
      businessCard: true,
    },
    type: 'business',
    creditScore: 'good',
    tags: ['travel', 'business', 'chase-ecosystem', 'bonus-hunter'],
    ecosystem: 'Chase',
    ecosystemRole: 'hub',
  },
  {
    id: 'ink-cash',
    name: 'Chase Ink Business Cash',
    issuer: 'Chase',
    network: 'Visa',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 750,
    signupBonusValue: 750,
    signupBonusSpend: 6000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Chase Ultimate Rewards',
    categories: {
      officeSupplies: 5,
      telecom: 5,
      gas: 2,
      dining: 2,
      everything: 1,
    },
    benefits: [
      'No annual fee',
      '5% on office supplies & telecom (up to $25k/year)',
      'Purchase protection',
      'Points combine with Sapphire for premium transfers',
    ],
    applicationRules: {
      rule5_24: true,
      businessCard: true,
    },
    type: 'business',
    creditScore: 'good',
    tags: ['cashback', 'no-fee', 'business', 'chase-ecosystem', 'companion'],
    ecosystem: 'Chase',
    ecosystemRole: 'spoke',
  },
  {
    id: 'ink-unlimited',
    name: 'Chase Ink Business Unlimited',
    issuer: 'Chase',
    network: 'Visa',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 750,
    signupBonusValue: 750,
    signupBonusSpend: 6000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Chase Ultimate Rewards',
    categories: {
      everything: 1.5,
    },
    benefits: [
      'No annual fee',
      '1.5% on everything',
      'Points combine with Sapphire for premium transfers',
      'Purchase protection',
    ],
    applicationRules: {
      rule5_24: true,
      businessCard: true,
    },
    type: 'business',
    creditScore: 'good',
    tags: ['cashback', 'no-fee', 'business', 'chase-ecosystem', 'companion'],
    ecosystem: 'Chase',
    ecosystemRole: 'spoke',
  },

  // ── AMERICAN EXPRESS ────────────────────────────────────────────────────────
  {
    id: 'amex-platinum',
    name: 'Amex Platinum',
    issuer: 'Amex',
    network: 'Amex',
    annualFee: 695,
    annualCredits: 695, // $200 airline, $200 hotel, $200 Uber Cash, $155 Walmart+, $100 Saks, etc.
    signupBonus: 80000,
    signupBonusValue: 1440,
    signupBonusSpend: 8000,
    signupBonusMonths: 6,
    rewardsCurrency: 'Amex Membership Rewards',
    categories: {
      flights: 5,
      amexTravelHotels: 5,
      everything: 1,
    },
    benefits: [
      '$200 airline fee credit',
      '$200 hotel credit (Fine Hotels + Resorts)',
      '$200 Uber Cash annually',
      '$155 Walmart+ credit',
      '$100 Saks Fifth Avenue credit',
      '$300 Equinox credit',
      '$189 CLEAR Plus credit',
      'Centurion Lounge access',
      'Priority Pass (access only)',
      'Global Entry / TSA PreCheck credit',
      'International Airline Program',
      'Fine Hotels + Resorts perks',
    ],
    applicationRules: {
      amexLifetime: true,
      amexCardLimit: true,
    },
    type: 'personal',
    creditScore: 'excellent',
    tags: ['travel', 'premium', 'luxury', 'amex-ecosystem', 'flagship', 'lounge'],
    ecosystem: 'Amex',
    ecosystemRole: 'hub',
  },
  {
    id: 'amex-gold',
    name: 'Amex Gold',
    issuer: 'Amex',
    network: 'Amex',
    annualFee: 250,
    annualCredits: 240, // $120 dining, $120 Uber Cash
    signupBonus: 60000,
    signupBonusValue: 1080,
    signupBonusSpend: 6000,
    signupBonusMonths: 6,
    rewardsCurrency: 'Amex Membership Rewards',
    categories: {
      dining: 4,
      groceries: 4, // US supermarkets up to $25k/year
      flights: 3,
      everything: 1,
    },
    benefits: [
      '$120 annual dining credit (Grubhub, The Cheesecake Factory, etc.)',
      '$120 annual Uber Cash',
      '4x at US supermarkets (up to $25,000/year)',
      '4x at restaurants worldwide',
      'No foreign transaction fees',
    ],
    applicationRules: {
      amexLifetime: true,
      amexCardLimit: true,
    },
    type: 'personal',
    creditScore: 'good',
    tags: ['dining', 'groceries', 'amex-ecosystem', 'mid-tier'],
    ecosystem: 'Amex',
    ecosystemRole: 'hub',
  },
  {
    id: 'amex-green',
    name: 'Amex Green',
    issuer: 'Amex',
    network: 'Amex',
    annualFee: 150,
    annualCredits: 100, // $100 LoungeBuddy, $100 CLEAR
    signupBonus: 40000,
    signupBonusValue: 720,
    signupBonusSpend: 3000,
    signupBonusMonths: 6,
    rewardsCurrency: 'Amex Membership Rewards',
    categories: {
      travel: 3,
      transit: 3,
      dining: 3,
      everything: 1,
    },
    benefits: [
      '$100 LoungeBuddy credit',
      '$100 CLEAR Plus credit',
      '3x on travel, transit, and dining',
    ],
    applicationRules: {
      amexLifetime: true,
      amexCardLimit: true,
    },
    type: 'personal',
    creditScore: 'good',
    tags: ['travel', 'dining', 'amex-ecosystem'],
    ecosystem: 'Amex',
    ecosystemRole: 'spoke',
  },
  {
    id: 'amex-bcp',
    name: 'Amex Blue Cash Preferred',
    issuer: 'Amex',
    network: 'Amex',
    annualFee: 95,
    annualCredits: 0,
    signupBonus: 300,
    signupBonusValue: 300,
    signupBonusSpend: 3000,
    signupBonusMonths: 6,
    rewardsCurrency: 'Cash',
    categories: {
      groceries: 6, // up to $6,000/year at US supermarkets
      streaming: 6,
      transit: 3,
      gas: 3,
      everything: 1,
    },
    benefits: [
      '6% at US supermarkets (up to $6,000/year)',
      '6% on select US streaming services',
      '3% on US gas stations and transit',
      'Return protection',
    ],
    applicationRules: {
      amexLifetime: true,
      amexCardLimit: true,
    },
    type: 'personal',
    creditScore: 'good',
    tags: ['cashback', 'groceries', 'gas', 'streaming'],
    ecosystem: 'Amex',
    ecosystemRole: 'cashback',
  },
  {
    id: 'amex-bce',
    name: 'Amex Blue Cash Everyday',
    issuer: 'Amex',
    network: 'Amex',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 200,
    signupBonusValue: 200,
    signupBonusSpend: 2000,
    signupBonusMonths: 6,
    rewardsCurrency: 'Cash',
    categories: {
      groceries: 3, // up to $6,000/year at US supermarkets
      onlineShopping: 3,
      gas: 3,
      everything: 1,
    },
    benefits: [
      'No annual fee',
      '3% at US supermarkets, US online retail, US gas stations (up to $6,000/year each)',
      'No foreign transaction fees on select purchases',
    ],
    applicationRules: {
      amexLifetime: true,
      amexCardLimit: true,
    },
    type: 'personal',
    creditScore: 'fair',
    tags: ['cashback', 'no-fee', 'groceries', 'gas'],
    ecosystem: 'Amex',
    ecosystemRole: 'cashback',
  },
  {
    id: 'amex-bbp',
    name: 'Amex Blue Business Plus',
    issuer: 'Amex',
    network: 'Amex',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 15000,
    signupBonusValue: 270,
    signupBonusSpend: 3000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Amex Membership Rewards',
    categories: {
      everything: 2, // up to $50,000/year
    },
    benefits: [
      'No annual fee',
      '2x on everything (up to $50,000/year)',
      'Points transfer to Amex transfer partners',
    ],
    applicationRules: {
      amexLifetime: true,
      businessCard: true,
    },
    type: 'business',
    creditScore: 'good',
    tags: ['no-fee', 'business', 'amex-ecosystem', 'companion'],
    ecosystem: 'Amex',
    ecosystemRole: 'spoke',
  },

  // ── CAPITAL ONE ─────────────────────────────────────────────────────────────
  {
    id: 'c1-venture-x',
    name: 'Capital One Venture X',
    issuer: 'Capital One',
    network: 'Visa',
    annualFee: 395,
    annualCredits: 300, // $300 Capital One Travel credit + 10k anniversary miles (~$150)
    signupBonus: 75000,
    signupBonusValue: 1125,
    signupBonusSpend: 4000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Capital One Miles',
    categories: {
      c1Travel: 10, // hotels & car rentals
      flights: 5,
      everything: 2,
    },
    benefits: [
      '$300 Capital One Travel credit',
      '10,000 anniversary bonus miles',
      'Capital One Lounge access',
      'Priority Pass lounge access',
      'Global Entry / TSA PreCheck credit',
      'Cell phone protection',
    ],
    applicationRules: {},
    type: 'personal',
    creditScore: 'excellent',
    tags: ['travel', 'premium', 'lounge', 'capital-one-ecosystem', 'flagship'],
    ecosystem: 'Capital One',
    ecosystemRole: 'hub',
  },
  {
    id: 'c1-venture',
    name: 'Capital One Venture',
    issuer: 'Capital One',
    network: 'Visa',
    annualFee: 95,
    annualCredits: 0,
    signupBonus: 75000,
    signupBonusValue: 1125,
    signupBonusSpend: 4000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Capital One Miles',
    categories: {
      c1Travel: 5,
      everything: 2,
    },
    benefits: [
      'Global Entry / TSA PreCheck credit',
      '2x on all purchases',
      'Transfer to 15+ travel partners',
    ],
    applicationRules: {},
    type: 'personal',
    creditScore: 'good',
    tags: ['travel', 'capital-one-ecosystem', 'simple'],
    ecosystem: 'Capital One',
    ecosystemRole: 'hub',
  },
  {
    id: 'c1-savor',
    name: 'Capital One Savor',
    issuer: 'Capital One',
    network: 'Mastercard',
    annualFee: 95,
    annualCredits: 0,
    signupBonus: 300,
    signupBonusValue: 300,
    signupBonusSpend: 3000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Capital One Miles',
    categories: {
      dining: 4,
      entertainment: 4,
      streaming: 4,
      groceries: 3,
      c1Entertainment: 8,
      everything: 1,
    },
    benefits: [
      '4% on dining, entertainment, and streaming',
      '3% at grocery stores',
      'No foreign transaction fees',
    ],
    applicationRules: {},
    type: 'personal',
    creditScore: 'good',
    tags: ['dining', 'entertainment', 'capital-one-ecosystem'],
    ecosystem: 'Capital One',
    ecosystemRole: 'spoke',
  },
  {
    id: 'c1-savorone',
    name: 'Capital One SavorOne',
    issuer: 'Capital One',
    network: 'Mastercard',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 200,
    signupBonusValue: 200,
    signupBonusSpend: 500,
    signupBonusMonths: 3,
    rewardsCurrency: 'Cash',
    categories: {
      dining: 3,
      entertainment: 3,
      streaming: 3,
      groceries: 3,
      everything: 1,
    },
    benefits: [
      'No annual fee',
      '3% on dining, entertainment, streaming, and groceries',
      'No foreign transaction fees',
    ],
    applicationRules: {},
    type: 'personal',
    creditScore: 'fair',
    tags: ['cashback', 'no-fee', 'dining', 'beginner-friendly'],
    ecosystem: 'Capital One',
    ecosystemRole: 'spoke',
  },

  // ── CITI ────────────────────────────────────────────────────────────────────
  {
    id: 'citi-strata-premier',
    name: 'Citi Strata Premier',
    issuer: 'Citi',
    network: 'Mastercard',
    annualFee: 95,
    annualCredits: 100, // $100 hotel savings
    signupBonus: 70000,
    signupBonusValue: 1120,
    signupBonusSpend: 4000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Citi ThankYou Points',
    categories: {
      hotels: 3,
      flights: 3,
      dining: 3,
      groceries: 3,
      gas: 3,
      everything: 1,
    },
    benefits: [
      '$100 hotel savings benefit annually',
      '3x on hotels, flights, dining, groceries, and gas',
      'Transfer to 16+ airline partners',
      'No foreign transaction fees',
    ],
    applicationRules: {
      citiCooldown: 24,
    },
    type: 'personal',
    creditScore: 'good',
    tags: ['travel', 'dining', 'groceries', 'gas', 'citi-ecosystem'],
    ecosystem: 'Citi',
    ecosystemRole: 'hub',
  },
  {
    id: 'citi-double-cash',
    name: 'Citi Double Cash',
    issuer: 'Citi',
    network: 'Mastercard',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 200,
    signupBonusValue: 200,
    signupBonusSpend: 1500,
    signupBonusMonths: 6,
    rewardsCurrency: 'Citi ThankYou Points',
    categories: {
      everything: 2, // 1% purchase + 1% pay
    },
    benefits: [
      'No annual fee',
      '2% on everything (1% when you buy + 1% when you pay)',
      'Points transfer to Citi transfer partners (with a Strata Premier)',
    ],
    applicationRules: {},
    type: 'personal',
    creditScore: 'fair',
    tags: ['cashback', 'no-fee', 'simple', 'beginner-friendly', 'citi-ecosystem'],
    ecosystem: 'Citi',
    ecosystemRole: 'spoke',
  },
  {
    id: 'citi-custom-cash',
    name: 'Citi Custom Cash',
    issuer: 'Citi',
    network: 'Mastercard',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 200,
    signupBonusValue: 200,
    signupBonusSpend: 1500,
    signupBonusMonths: 6,
    rewardsCurrency: 'Citi ThankYou Points',
    categories: {
      topCategory: 5, // 5% on top eligible category up to $500/month
      everything: 1,
    },
    benefits: [
      'No annual fee',
      '5% on your top eligible spend category each billing cycle (up to $500/month)',
      'Eligible categories: restaurants, gas, groceries, select travel, select transit, streaming, pharmacies, home improvement stores, fitness clubs, live entertainment',
    ],
    applicationRules: {},
    type: 'personal',
    creditScore: 'fair',
    tags: ['cashback', 'no-fee', 'flexible', 'citi-ecosystem'],
    ecosystem: 'Citi',
    ecosystemRole: 'spoke',
  },

  // ── DISCOVER ────────────────────────────────────────────────────────────────
  {
    id: 'discover-it',
    name: 'Discover it Cash Back',
    issuer: 'Discover',
    network: 'Discover',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 0,
    signupBonusValue: 0, // Cashback Match in first year (effectively 2x first year)
    signupBonusSpend: 0,
    signupBonusMonths: 0,
    rewardsCurrency: 'Discover Cashback',
    categories: {
      rotating: 5, // up to $1,500/quarter
      everything: 1,
    },
    benefits: [
      'No annual fee',
      'Cashback Match: Discover doubles all cash back earned at end of first year',
      '5% on rotating quarterly categories (up to $1,500/quarter)',
      'No foreign transaction fees',
      'Free FICO credit score',
    ],
    applicationRules: {},
    type: 'personal',
    creditScore: 'fair',
    tags: ['cashback', 'no-fee', 'rotating', 'beginner-friendly'],
    ecosystem: 'Discover',
    ecosystemRole: 'standalone',
  },

  // ── BANK OF AMERICA ─────────────────────────────────────────────────────────
  {
    id: 'boa-premium-rewards',
    name: 'BofA Premium Rewards',
    issuer: 'Bank of America',
    network: 'Visa',
    annualFee: 95,
    annualCredits: 100, // $100 airline incidental credit
    signupBonus: 60000,
    signupBonusValue: 600,
    signupBonusSpend: 4000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Cash',
    categories: {
      travel: 2,
      dining: 2,
      everything: 1.5,
    },
    benefits: [
      '$100 annual airline incidental credit',
      '$100 Global Entry / TSA PreCheck credit every 4 years',
      '25–75% rewards bonus with Preferred Rewards membership',
      'No foreign transaction fees',
    ],
    applicationRules: {},
    type: 'personal',
    creditScore: 'good',
    tags: ['travel', 'cashback', 'boa-ecosystem'],
    ecosystem: 'Bank of America',
    ecosystemRole: 'hub',
  },
  {
    id: 'boa-customized-cash',
    name: 'BofA Customized Cash Rewards',
    issuer: 'Bank of America',
    network: 'Visa',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 200,
    signupBonusValue: 200,
    signupBonusSpend: 1000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Cash',
    categories: {
      choiceCategory: 3, // online shopping, gas, dining, travel, drug stores, or home improvement
      groceries: 2, // up to $2,500/quarter combined with choice
      everything: 1,
    },
    benefits: [
      'No annual fee',
      '3% on your choice category (online shopping, gas, dining, travel, drug stores, or home improvement)',
      '2% on grocery stores and wholesale clubs (up to $2,500/quarter combined)',
      'Rewards bonus with Preferred Rewards',
    ],
    applicationRules: {},
    type: 'personal',
    creditScore: 'fair',
    tags: ['cashback', 'no-fee', 'flexible', 'beginner-friendly'],
    ecosystem: 'Bank of America',
    ecosystemRole: 'standalone',
  },

  // ── WELLS FARGO ─────────────────────────────────────────────────────────────
  {
    id: 'wf-autograph',
    name: 'Wells Fargo Autograph',
    issuer: 'Wells Fargo',
    network: 'Visa',
    annualFee: 0,
    annualCredits: 0,
    signupBonus: 20000,
    signupBonusValue: 200,
    signupBonusSpend: 1000,
    signupBonusMonths: 3,
    rewardsCurrency: 'Cash',
    categories: {
      dining: 3,
      travel: 3,
      gas: 3,
      transit: 3,
      streaming: 3,
      phone: 3,
      everything: 1,
    },
    benefits: [
      'No annual fee',
      '3x on restaurants, travel, gas, transit, streaming, and phone plans',
      'Cell phone protection',
      'No foreign transaction fees',
    ],
    applicationRules: {},
    type: 'personal',
    creditScore: 'good',
    tags: ['cashback', 'no-fee', 'dining', 'gas', 'travel'],
    ecosystem: 'Wells Fargo',
    ecosystemRole: 'standalone',
  },
];

/**
 * Returns a card by its id.
 */
function getCardById(id) {
  return CARDS.find(c => c.id === id) || null;
}

/**
 * Returns all cards, optionally filtered by issuer.
 */
function getCardsByIssuer(issuer) {
  return CARDS.filter(c => c.issuer === issuer);
}
